### ISSUE TITLE
Cannot switch to old mode

### ISSUE THREAD

**Issue by pyrsmk** [teambition/merge2#9]
Hi!

I've a weird issue when using merge2. It seems it comes from the fact I'm splitting my stream pipes. But I'm not sure how to fix this, and how to do this differently...

``` js
var streams = require('merge2')(),
requireTree = function(name) {
    var stream = gulp.src( components[name] + '/component.scss' );
    if(fs.existsSync(components[name] + '/require.json')) {
        var deps = require(components[name] + '/require.json'),
            i, j;
        for(i=deps.length-1, j=0; i>=j; --i) {
            requireTree(deps[i]);
            stream.pipe( insert.append('@import "' + components[deps[i]] + '/component.scss";') );
        }
    }
    stream.pipe( gulp.dest(rootPath + '/cache/scss/' + name) );
    streams.add(stream);
};
```

**Comment by jjalonso** [comment]
Same here. 

That happened as well the same with "streamqueue" lib, then I can guess is something of node, but... How to avoid it or why ?

Thanks.

**Comment by pyrsmk** [comment]
Personnally, I fixed the issue without not really fixing it but by structuring my code differently ^^

**Comment by jjalonso** [comment]
I came again back to 'streamqueue' and I discovered was the .queue() or
.add() (depend of beach lib) the guilty of the error.

But if you deliver all gulp src in the constructor everything works.

Then... Because I had and array... I called the constructor with apply() to
spread the streams array as comma separated arguments.
